# Generated by Django 5.0.6 on 2024-07-07 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_partners', '0002_alter_businesspartner_code'),
        ('sales', '0004_remove_salesdocument_number_salesdocument_doc_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person_name', models.CharField(max_length=100)),
                ('activity_type', models.CharField(choices=[('phone_call', 'Phone Call'), ('visit', 'Visit'), ('campaign', 'Campaign'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_partners.businesspartner')),
                ('sales_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesdocument')),
            ],
        ),
    ]
