# Generated by Django 5.0.6 on 2024-07-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
