# Generated by Django 5.0.6 on 2024-07-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdocument',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
