# Generated by Django 5.0.6 on 2024-07-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesdocument_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdocument',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
