# Generated by Django 5.0.6 on 2024-07-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesdocument_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdocument',
            name='number',
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='doc_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
